// seeders/demodataSurvey.js
import mongoose from "mongoose";
import dotenv from "dotenv";
dotenv.config();

import House from "../models/House.js";
import Survey from "../models/Survey.js";
import Village from "../models/Village.js";
import { PMJAY_DOMAINS } from "../config/pmjayDomains.js";

// -----------------------------------------
// 1) CONNECT TO DB
// -----------------------------------------
console.log("⏳ Connecting to MongoDB...");

await mongoose.connect(process.env.MONGO_URI);

console.log("📌 Connected!");


// -----------------------------------------
// 2) EXISTING BLOCK ID (DO NOT CHANGE)
// -----------------------------------------
const BLOCK_ID = "6925b40c6caec3c330b54f13";

// -----------------------------------------
// 3) NEW VILLAGE ID FOR SEEDING
// -----------------------------------------
const VILLAGE_ID = new mongoose.Types.ObjectId();

// -----------------------------------------
// CREATE VILLAGE
// -----------------------------------------
async function createVillage() {
  const village = await Village.create({
    _id: VILLAGE_ID,
    name: "Demo Survey Village",
    block: BLOCK_ID,
    totalPopulation: 2400,
    scPopulation: { count: 620 },
    location: { lat: 12.9001, lng: 79.0812 }
  });

  console.log("🏡 Village Created:", village._id.toString());
}


// -----------------------------------------
// HOUSE DATA
// -----------------------------------------
const housesData = [
  { number: "1A", members: ["Raja", "Preethi", "Kumar"] },
  { number: "2B", members: ["Arun", "Lakshmi"] },
  { number: "3C", members: ["Suresh"] },
  { number: "4D", members: ["Devi", "Mohan"] },
  { number: "5E", members: ["Kannan", "Selvi", "Priya"] },
];

// -----------------------------------------
// CREATE HOUSES
// -----------------------------------------
async function createHouses() {
  const houseIds = [];

  for (const h of housesData) {
    const house = await House.create({
      village: VILLAGE_ID,
      houseNumber: h.number,
      members: h.members,
      membersCount: h.members.length,
      createdBy: new mongoose.Types.ObjectId(),
      surveyStatus: "completed",
    });

    houseIds.push(house._id);
  }

  console.log("🏠 Houses Created:", houseIds.length);
  return houseIds;
}


// -----------------------------------------
// GENERATE RANDOM SURVEY ANSWERS
// -----------------------------------------
function generateIndicators() {
  const indicators = [];

  Object.entries(PMJAY_DOMAINS).forEach(([domainKey, domain]) => {
    domain.indicators.forEach(ind => {
      const entry = {
        indicatorId: ind.id,
        domain: domainKey,
        question: ind.sector,
        answerType: ind.type,
        answer: null,
        percentage: null,
        score: 0, // auto-generated by pre-save
        remark: ""
      };

      if (ind.type === "yes_no") {
        entry.answer = Math.random() > 0.5 ? "yes" : "no";
      }

      if (ind.type === "percentage") {
        entry.percentage = Math.floor(Math.random() * 100);
      }

      indicators.push(entry);
    });
  });

  return indicators;
}


// -----------------------------------------
// CREATE SURVEYS (TRIGGER SCORE CALCULATION)
// -----------------------------------------
async function createSurveys(houseIds) {
  let count = 0;

  for (const houseId of houseIds) {
    const indicators = generateIndicators();

    const survey = new Survey({
      house: houseId,
      village: VILLAGE_ID,
      indicators,
      status: "completed",
      surveyTakenBy: {
        name: "Seeder Bot",
        user: new mongoose.Types.ObjectId(),
      },
      members: ["Auto", "Generated"],
      membersCount: 2
    });

    // 🔥 IMPORTANT: FORCE TRIGGER AUTO SCORING
    survey.markModified("indicators");
    await survey.save();

    count++;
  }

  console.log(`📝 Surveys Created: ${count}`);
}


// -----------------------------------------
// RUN ALL SEEDS
// -----------------------------------------
async function run() {
  console.log("⚠️ Clearing old data...");
  
  await Survey.deleteMany({});
  await House.deleteMany({});
  await Village.deleteMany({});

  console.log("🧹 Database Cleared!");

  await createVillage();

  const houseIds = await createHouses();

  await createSurveys(houseIds);

  console.log("🎯 DONE — Seed data ready for Dashboard!");

  process.exit(0);
}

run();
